### ISSUE TITLE
Loading Comments stopped working.

### ISSUE THREAD

**Issue by programmer1o1** [sonigy/YCS#56]
Clicking "reload" on the comments doesn't load the comments anymore or just loading doesn't work anymore. Please fix it. Thanks you so much.

**Comment by NicPalacio** [comment]
Exactly it happen for me recently too , it does not work in any browser

@sonigy  any idea why ? If you need help I will be happy to contribute but I think that it has todo with something more technical.

**Comment by chuimoi** [comment]
For me, it doesn't work with firefox

**Comment by JackOfSpade** [comment]
Guys, the author has probably died by now. Just move on to another chrome extension. There are plenty.

**Comment by programmer1o1** [comment]
> Guys, the author has probably died by now. Just move on to another chrome extension. There are plenty.

To be fair, it's the best one right now. There aren't many good extensions like these in Firefox, and maybe Chrome too.

**Comment by NicPalacio** [comment]
@JackOfSpade  mm not sure why you say that xD, but there us not really an alternative to this extension, only this one does the work

**Comment by RenegadeScooter** [comment]
I use Brave (version 1.64.113, Chromium 123.0.6312.86, 64-bit).
The extension loads comments for normal windows, but not private windows.

**Comment by knoajp** [comment]
@NicPalacio Thank you for mentioning me😆, by quick investigation, it does load comments but only fails to handle/show.
Although I haven't checked the extension code yet, it could be caused by just a JSON structural modification by YouTube.

As well as making a quick patch on the YCS, I expect some nice alternatives to appear, like the IYCS project. 😉
https://github.com/StellarSt0rm/IYCS
@StellarSt0rm

**Comment by knoajp** [comment]
🤔 It seems to take much effort to solve it...

YCS source code on Mac Chrome (minified):
Library/Application Support/Google/Chrome/Default/Extensions/pmfhcilikeembgbiadjiojgfgcfbcoaa/1.1.12_0/web-resources/wresources.js

JSON API:
https://www.youtube.com/youtubei/v1/next?key=xxxx

Currently, comments are in:
JSON.frameworkUpdates.entityBatchUpdate.mutations

But there are no such property names in wresources.js.
Still, I can find JSON.onResponseReceivedEndpoints in wresources.js, which might haven't changed.

**Comment by knoajp** [comment]
My biggest reason for using YCS is to browse popular comments by Likes order.
So my temporal workaround is using the CSS below to highlight popular comments.

```css
#vote-count-middle{
  color: black !important;
  border-radius: .5em;
  padding: .25em .5em;
}
#vote-count-middle/*1000-*/:is([aria-label$="K likes"],[aria-label$="M likes"]){
  font-weight: bold;
  background: #f008;
  border: 1px solid #f00f;
}
#vote-count-middle/*100-999*/{
  background: #f004;
  border: 1px solid #f008;
}
#vote-count-middle/*10-99*/:is(
  [aria-label^="10 "],[aria-label^="11 "],[aria-label^="12 "],[aria-label^="13 "],[aria-label^="14 "],[aria-label^="15 "],[aria-label^="16 "],[aria-label^="17 "],[aria-label^="18 "],[aria-label^="19 "],
  [aria-label^="20 "],[aria-label^="21 "],[aria-label^="22 "],[aria-label^="23 "],[aria-label^="24 "],[aria-label^="25 "],[aria-label^="26 "],[aria-label^="27 "],[aria-label^="28 "],[aria-label^="29 "],
  [aria-label^="30 "],[aria-label^="31 "],[aria-label^="32 "],[aria-label^="33 "],[aria-label^="34 "],[aria-label^="35 "],[aria-label^="36 "],[aria-label^="37 "],[aria-label^="38 "],[aria-label^="39 "],
  [aria-label^="40 "],[aria-label^="41 "],[aria-label^="42 "],[aria-label^="43 "],[aria-label^="44 "],[aria-label^="45 "],[aria-label^="46 "],[aria-label^="47 "],[aria-label^="48 "],[aria-label^="49 "],
  [aria-label^="50 "],[aria-label^="51 "],[aria-label^="52 "],[aria-label^="53 "],[aria-label^="54 "],[aria-label^="55 "],[aria-label^="56 "],[aria-label^="57 "],[aria-label^="58 "],[aria-label^="59 "],
  [aria-label^="60 "],[aria-label^="61 "],[aria-label^="62 "],[aria-label^="63 "],[aria-label^="64 "],[aria-label^="65 "],[aria-label^="66 "],[aria-label^="67 "],[aria-label^="68 "],[aria-label^="69 "],
  [aria-label^="70 "],[aria-label^="71 "],[aria-label^="72 "],[aria-label^="73 "],[aria-label^="74 "],[aria-label^="75 "],[aria-label^="76 "],[aria-label^="77 "],[aria-label^="78 "],[aria-label^="79 "],
  [aria-label^="80 "],[aria-label^="81 "],[aria-label^="82 "],[aria-label^="83 "],[aria-label^="84 "],[aria-label^="85 "],[aria-label^="86 "],[aria-label^="87 "],[aria-label^="88 "],[aria-label^="89 "],
  [aria-label^="90 "],[aria-label^="91 "],[aria-label^="92 "],[aria-label^="93 "],[aria-label^="94 "],[aria-label^="95 "],[aria-label^="96 "],[aria-label^="97 "],[aria-label^="98 "],[aria-label^="99 "],
dummy){
  background: #f002;
  border: 1px solid #f004;
}
#vote-count-middle/*1-9*/:is(
  [aria-label^="1 "],[aria-label^="2 "],[aria-label^="3 "],[aria-label^="4 "],[aria-label^="5 "],[aria-label^="6 "],[aria-label^="7 "],[aria-label^="8 "],[aria-label^="9 "],
dummy){
  background: #f001;
  border: 1px solid #f002;
}
```
